name: Docker build and push

on:
  workflow_run:
    workflows:
      - On merge feature to dev
    types:
      - completed

jobs:
  build-test-deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: frontend dependencies
        working-directory: ./frontend
        run: npm install

      - name: backend dependencies
        working-directory: ./backend
        run: npm install

      - name: backend tests
        working-directory: ./backend
        run: npm test 

      - name: Set up Git credentials
        run: |
          git config --global user.name "AbelB"
          git config --global user.email "abel8177@gmail.com"

      - name: Checkout main
        run: |
          git checkout main

      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker
        run: |
          docker-compose build

      - name: Push Docker 
        run: |
          docker-compose push